Repository road-maker/road-maker-spring, pull requests merged in 2023-07, with the labels that each got.

#15 [#1] Feat: JWT 발급 및 authentication
  log/test.log
  log/test.log.2023-07-18.0.gz
  src/main/java/com/roadmaker/commons/config/SecurityConfig.java
  src/main/java/com/roadmaker/member/authentication/JwtAuthenticationFilter.java
  src/main/java/com/roadmaker/member/authentication/JwtProvider.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/domain/entity/Member.java
  src/main/java/com/roadmaker/member/service/CustomUserDetailsService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
Labels: backend

#25 [#18] Feat : Add formatting to the prompt
  log/test.log
  log/test.log.2023-07-21.0.gz
  src/main/java/com/roadmaker/gpt/controller/GptController.java
Labels: Feat

#33 [#18] Fix : Fix timeout error
  src/main/java/com/roadmaker/gpt/controller/GptController.java
Labels: fix

#34 [#18] Fix : change api address
  src/main/java/com/roadmaker/gpt/controller/GptController.java
Labels: fix

#37 [#35] Feat : add check problem, add Security
  build.gradle
  src/main/java/com/roadmaker/boj/controller/BojController.java
  src/main/java/com/roadmaker/commons/config/SecurityConfig.java
Labels: Feat

#38 [#21] Feat: 로드맵 수행 API
  log/test.log
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNode.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNodeRepository.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressroadmap/InProgressRoadmap.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressroadmap/InProgressRoadmapRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/Roadmap.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapedge/RoadmapEdge.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapeditor/RoadmapEditor.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapnode/RoadmapNode.java
Labels: Feat

#51 [#47] Feat: Mypage & User data edit
  log/test.log
  src/main/java/com/roadmaker/member/authentication/SecurityUtil.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/dto/MypageRequest.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/member/service/MemberService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/dto/InProgressRoadmapDto.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNodeRepository.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressroadmap/InProgressRoadmapRepository.java
Labels: Feat

#56 FIX(joinRoadmap & nodeDone): Controller & Service splitted
  build.gradle
  log/test.log
  src/main/java/com/roadmaker/gpt/dto/Sentence.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/dto/LoginRequest.java
  src/main/java/com/roadmaker/member/dto/MypageRequest.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/service/MemberService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/InProgressRoadmapDto.java
  src/main/java/com/roadmaker/roadmap/dto/NodeStatusChangeDto.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNodeRepository.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Refactor, fix

#59 [Closes #10]Feat(ìRoadmap): Added API for showing all roadmaps with owner nickname information
  log/test.log
  src/main/java/com/roadmaker/commons/BaseTimeEntity.java
  src/main/java/com/roadmaker/commons/interceptor/LoginRequiredInterceptor.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapDto.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapedge/RoadmapEdgeRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapeditor/RoadmapEditorRepository.java
Labels: Feat

#60 Feat(Roadmap): Added Avatar Url to getRoadmaps() return entity
  log/test.log
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapDto.java
Labels: Feat

#66 [#18] Feat : add detect language
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/gpt/dto/GptRoadmapRequest.java
  src/main/java/com/roadmaker/gpt/dto/GptRoadmapResponse.java
Labels: Feat

#67 [#67] Fix : response only korean
  src/main/java/com/roadmaker/gpt/controller/GptController.java
Labels: fix

#71 [#70]Feat: Comment Api added
  log/test.log
  log/test.log.2023-07-26.0.gz
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/CommentDto.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapRequest.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapResponse.java
  src/main/java/com/roadmaker/roadmap/entity/comment/Comment.java
  src/main/java/com/roadmaker/roadmap/entity/comment/CommentRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/Roadmap.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Feat

#72 [#70] FIX(Comment API): Confict Fixed
  log/test.log
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapResponse.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: fix

#74 [#18] Feat : add detail content
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/gpt/dto/GptDetailResponse.java
Labels: Feat

#87 [#86] Refactor(Comment): refactoring comment package
  src/main/java/com/roadmaker/comment/controller/CommentController.java
  src/main/java/com/roadmaker/comment/dto/CommentDto.java
  src/main/java/com/roadmaker/comment/entity/Comment.java
  src/main/java/com/roadmaker/comment/entity/CommentRepository.java
  src/main/java/com/roadmaker/comment/service/CommentService.java
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapResponse.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepository.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Refactor

#96 FIX(MemberService - profile save): Added Exception for duplicated uwe…
  src/main/java/com/roadmaker/comment/controller/CommentController.java
  src/main/java/com/roadmaker/comment/dto/CommentDto.java
  src/main/java/com/roadmaker/comment/entity/Comment.java
  src/main/java/com/roadmaker/comment/entity/CommentRepository.java
  src/main/java/com/roadmaker/comment/service/CommentService.java
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapResponse.java
Labels: fix

#97 [#89] FEAT(Comment - pagination): now available pagination feature fo…
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
Labels: Feat

#99 Refactor(MemberService): returning response body when user changed us…
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/dto/MemberResponse.java
  src/main/java/com/roadmaker/member/dto/MypageRequest.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/member/service/MemberService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapDto.java
Labels: Refactor, fix

#100 Fix(MemberEntity): Activated BlogUrl field of member class
  src/main/java/com/roadmaker/member/dto/MemberResponse.java
  src/main/java/com/roadmaker/member/dto/MypageRequest.java
  src/main/java/com/roadmaker/member/dto/MypageResponse.java
  src/main/java/com/roadmaker/member/dto/SignupRequest.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/member/service/MemberService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Refactor

#117 Fix(MemberController): findmember => changed argument from nickname ...
  src/main/java/com/roadmaker/comment/controller/CommentController.java
  src/main/java/com/roadmaker/comment/dto/CommentDto.java
  src/main/java/com/roadmaker/comment/service/CommentService.java
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
Labels: Refactor

#121 Fix(MemberController): findMember - now method throws NotFoundExcepti…
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/member/service/MemberService.java
  src/main/java/com/roadmaker/member/service/MemberServiceImpl.java
Labels: fix
