Repository road-maker/road-maker-spring, pull requests merged in 2023-08, with the labels that each got.

#147 [#123] Feat(Roadmap): Search Api with QueryDSL
  build.gradle
  src/main/java/com/roadmaker/comment/controller/CommentController.java
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/commons/config/QuerydslConfiguration.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepositoryCustom.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepositoryImpl.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Feat

#160 Like roadmap
  src/main/java/com/roadmaker/like/controller/LikeController.java
  src/main/java/com/roadmaker/like/entity/Like.java
  src/main/java/com/roadmaker/like/entity/LikeRepository.java
  src/main/java/com/roadmaker/like/service/LikeService.java
  src/main/java/com/roadmaker/like/service/LikeServiceImpl.java
Labels: Refactor

#172 Fix(paging): now ip address is hidden
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: fix

#176 [#175] Feat : added a response for the number of likes
  src/main/java/com/roadmaker/like/controller/LikeController.java
  src/main/java/com/roadmaker/like/dto/LikeRoadmapResponse.java
Labels: Feat

#177 [#177] Fix : change boolean name
  src/main/java/com/roadmaker/like/dto/LikeRoadmapResponse.java
Labels: fix

#178 Fix(Pagination): removed size param
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepositoryImpl.java
Labels: Refactor, fix

#205 [Close #185]Feat(RoadmapService): Calling roadmap list now have options of most-l…
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/gpt/service/GptService.java
  src/main/java/com/roadmaker/gpt/service/GptServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepositoryCustom.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepositoryImpl.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Refactor, Feat

#208 [#174]Feat(GptService) & Fix(MemberControl): Now node details receives gpt …
  src/main/java/com/roadmaker/commons/config/TaskExecutorConfig.java
  src/main/java/com/roadmaker/commons/event/CloseHandler.java
  src/main/java/com/roadmaker/commons/exception/ExecutionException.java
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/gpt/dto/GptDetailResponse.java
  src/main/java/com/roadmaker/gpt/dto/GptRoadmapResponse.java
  src/main/java/com/roadmaker/gpt/dto/NodeDetail.java
  src/main/java/com/roadmaker/gpt/dto/RoadmapData.java
  src/main/java/com/roadmaker/gpt/service/GptService.java
  src/main/java/com/roadmaker/gpt/service/GptServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
Labels: Refactor, Feat

#209 Fix(gptService): roadmap making api returns roadmap with only nodes …
  src/main/java/com/roadmaker/gpt/controller/GptController.java
Labels: fix

#212 [#174]Feature(GptController): separate multithreading gpt caller(detailContentsThread), Fix(RoadmapEntity): description field(String) limitation changed from…
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/Roadmap.java
Labels: fix

#217 Feat : added checking own blog
  src/main/java/com/roadmaker/blog/dto/CertifiedBlogRequest.java
  src/main/java/com/roadmaker/blog/entity/certifiedblog/CertifiedBlog.java
  src/main/java/com/roadmaker/blog/service/CertifiedBlogServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/entity/blogkeyword/BlogKeyword.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNodeRepository.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Feat

#220 Feat(GptService), Refactor(CommentDto): gpt api modified, now comment…
  src/main/java/com/roadmaker/comment/dto/CommentDto.java
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/gpt/service/GptServiceImpl.java
  src/main/java/com/roadmaker/inprogressroadmap/entity/InProgressRoadmapRepository.java
  src/main/java/com/roadmaker/member/entity/Member.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
Labels: Refactor, Feat

#222 Feat(GptService, GptController): prompting changed for better gpt-ans…
  src/main/java/com/roadmaker/gpt/controller/GptController.java
  src/main/java/com/roadmaker/gpt/service/GptServiceImpl.java
Labels: Feat

#223 Fix(RoadmapDto, CommentDto): DateTimeFormatter now format date into y…
  src/main/java/com/roadmaker/comment/dto/CommentDto.java
  src/main/java/com/roadmaker/roadmap/dto/RoadmapDto.java
Labels: fix

#230 Fix(GptService): Gpt response now replaces consecutive newline charac…
  src/main/java/com/roadmaker/gpt/service/GptServiceImpl.java
Labels: fix

#233 Fix(TaskExecutorConfig): Now ThreadPoolTaskExecutor sets MaxPoolSize …
  src/main/java/com/roadmaker/commons/config/TaskExecutorConfig.java
Labels: fix

#237 Fix(CommentService, RoadmapService): Comment ordering enabled, null l…
  src/main/java/com/roadmaker/comment/service/CommentServiceImpl.java
  src/main/java/com/roadmaker/member/controller/MemberController.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: fix

#238 Fix(RaodmapService): If inProgressroadmap is not found, empty entity …
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: fix

#239 Fix(CommentService, InProgressRoadmap/RoadmapService): Data response …
  src/main/java/com/roadmaker/inprogressroadmap/entity/InProgressRoadmapRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmap/RoadmapRepository.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: fix

#242 블로그 인증 방식 수정
  src/main/java/com/roadmaker/blog/service/CertifiedBlogServiceImpl.java
  src/main/java/com/roadmaker/roadmap/controller/RoadmapController.java
  src/main/java/com/roadmaker/roadmap/dto/CreateRoadmapRequest.java
  src/main/java/com/roadmaker/roadmap/entity/blogkeyword/BlogKeyword.java
  src/main/java/com/roadmaker/roadmap/entity/blogkeyword/BlogKeywordRepository.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapnode/RoadmapNode.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapService.java
  src/main/java/com/roadmaker/roadmap/service/RoadmapServiceImpl.java
Labels: Refactor, Feat

#243 [Refactor] : Adding keywords when loading roadmaps
  src/main/java/com/roadmaker/roadmap/dto/RoadmapNodeDto.java
  src/main/java/com/roadmaker/roadmap/entity/blogkeyword/BlogKeyword.java
  src/main/java/com/roadmaker/roadmap/entity/inprogressnode/InProgressNode.java
Labels: Refactor

#246 [Fix] : Added null error handling
  src/main/java/com/roadmaker/blog/dto/CertifiedBlogResponse.java
  src/main/java/com/roadmaker/blog/service/CertifiedBlogServiceImpl.java
Labels: fix

#247 [Fix] : Add error handling
  build.gradle
  src/main/java/com/roadmaker/blog/dto/CertifiedBlogRequest.java
  src/main/java/com/roadmaker/blog/dto/CertifiedBlogResponse.java
  src/main/java/com/roadmaker/blog/entity/certifiedblog/CertifiedBlog.java
  src/main/java/com/roadmaker/blog/service/CertifiedBlogServiceImpl.java
Labels: fix

#249 [Fix] : Made possible by blog keywordId
  src/main/java/com/roadmaker/blog/dto/CertifiedBlogRequest.java
  src/main/java/com/roadmaker/blog/service/CertifiedBlogServiceImpl.java
  src/main/java/com/roadmaker/roadmap/entity/roadmapnode/RoadmapNode.java
Labels: fix
